export const FETCH_CRYPTOS_START = 'FETCH_CRYPTOS_START'
export const FETCH_CRYPTOS_SUCCESS = 'FETCH_CRYPTOS_SUCCESS'
export const FETCH_CRYPTOS_FAIL = 'FETCH_CRYPTOS_FAIL'

export const FETCH_CRYPTO_START = 'FETCH_CRYPTO_START'
export const FETCH_CRYPTO_SUCCESS = 'FETCH_CRYPTO_SUCCESS'
export const FETCH_CRYPTO_FAIL = 'FETCH_CRYPTO_FAIL'

export const FETCH_BITCOIN_START = 'FETCH_BITCOIN_START'
export const FETCH_BITCOIN_SUCCESS = 'FETCH_BITCOIN_SUCCESS'
export const FETCH_BITCOIN_FAIL = 'FETCH_BITCOIN_FAIL'

export const SET_CURRENCY = 'SET_CURRENCY'

export const SET_CRYPTO = 'SET_CRYPTO'